// Generated by CoffeeScript 1.4.0
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'underscore', 'input/television/television-commercial-on-camera', 'input/television/television-commercial-off-camera', 'input/television/television-commercial-demo'], function($, _, TelevisionCommercialOnCamera, TelevisionCommercialOffCamera, TelevisionCommercialDemo) {
    var exports;
    exports = {
      'OnCamera': TelevisionCommercialOnCamera,
      'OffCamera': TelevisionCommercialOffCamera,
      'Demo': TelevisionCommercialDemo
    };
    return exports;
  });

}).call(this);
