// Generated by CoffeeScript 1.6.1
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery'], function($) {
    var PrincipalActor,
      _this = this;
    PrincipalActor = (function() {

      function PrincipalActor(index) {
        var _this = this;
        this.index = index;
        this.onInputActors = function(event) {
          return PrincipalActor.prototype.onInputActors.apply(_this, arguments);
        };
        this.html = "<fieldset>\n  I'll need\n  <input type=\"number\" name=\"num-actors\" id=\"num-actors\" value=\"0\" min=\"0\" max=\"2\">\n  <a href=\"#principal-actor\" class=\"term open\">principal actor</a>(s).\n</fieldset>";
        this.$el = $(this.html);
        this.el = this.$el[0];
        this.$el.on('input change', '#num-actors', this.onInputActors);
      }

      PrincipalActor.prototype.onInputActors = function(event) {};

      return PrincipalActor;

    })();
    return PrincipalActor;
  });

}).call(this);
