// Generated by CoffeeScript 1.6.1
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'touchable/touchable'], function($, Touchable) {
    var DraggableNumber,
      _this = this;
    root.isNumberDragging = false;
    DraggableNumber = (function() {

      function DraggableNumber(element, options) {
        var _this = this;
        this.element = element;
        this.options = options;
        this.onTouchableUp = function(event, touches) {
          return DraggableNumber.prototype.onTouchableUp.apply(_this, arguments);
        };
        this.onTouchableMove = function(event, touches) {
          return DraggableNumber.prototype.onTouchableMove.apply(_this, arguments);
        };
        this.onTouchableDown = function(event, touches) {
          return DraggableNumber.prototype.onTouchableDown.apply(_this, arguments);
        };
        this.onMouseLeave = function(event) {
          return DraggableNumber.prototype.onMouseLeave.apply(_this, arguments);
        };
        this.onMouseEnter = function(event) {
          return DraggableNumber.prototype.onMouseEnter.apply(_this, arguments);
        };
        this.$ele = $(this.element).addClass('draggable-number');
        this.initializeHover();
        this.initializeHelp();
        this.initializeDrag();
        return;
      }

      DraggableNumber.prototype.initializeHover = function() {
        this.isHovering = false;
        this.$ele.on({
          'mouseenter': this.onMouseEnter,
          'mouseleave': this.onMouseLeave
        });
      };

      DraggableNumber.prototype.initializeHelp = function() {
        var isInput;
        isInput = this.$ele.is('input');
        this.$help = $("<div class=\"number-help\">" + (isInput ? 'click or ' : '') + "drag</div>");
        if (isInput) {
          this.$ele.wrap("<span style=\"display: inline-block; position: relative;\" />");
          this.$help.insertAfter(this.$ele).hide();
        } else {
          this.$help.prependTo(this.$ele).hide();
        }
      };

      DraggableNumber.prototype.initializeDrag = function() {
        this.isDragging = false;
        this.touchable = new Touchable(this.element);
        this.$ele.on({
          'touchabledown': this.onTouchableDown,
          'touchablemove': this.onTouchableMove,
          'touchableup': this.onTouchableUp
        });
      };

      DraggableNumber.prototype.onMouseEnter = function(event) {
        this.isHovering = true;
        this.updateRollOver();
      };

      DraggableNumber.prototype.onMouseLeave = function(event) {
        this.isHovering = false;
        this.updateRollOver();
      };

      DraggableNumber.prototype.onTouchableDown = function(event, touches) {
        var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8;
        this.min = (_ref = (_ref1 = this.$ele.attr('min')) != null ? _ref1 : (_ref2 = this.options) != null ? _ref2.min : void 0) != null ? _ref : 0;
        this.max = (_ref3 = (_ref4 = this.$ele.attr('max')) != null ? _ref4 : (_ref5 = this.options) != null ? _ref5.max : void 0) != null ? _ref3 : 1e100;
        this.step = (_ref6 = (_ref7 = this.$ele.attr('step')) != null ? _ref7 : (_ref8 = this.options) != null ? _ref8.step : void 0) != null ? _ref6 : 1;
        this.valStart = parseInt(this.$ele.val(), 10 || 0);
        this.isDragging = root.isNumberDragging = true;
        this.updateRollOver();
      };

      DraggableNumber.prototype.onTouchableMove = function(event, touches) {
        var value;
        value = parseInt(this.valStart, 10) + touches.translation.x / 5 * this.step;
        value = Math.min(Math.max(this.min, Math.round(value / this.step) * this.step), this.max);
        this.$ele.val(value).trigger('change');
        this.updateHelp();
      };

      DraggableNumber.prototype.onTouchableUp = function(event, touches) {
        var _ref;
        this.isDragging = root.isNumberDragging = false;
        this.updateRollOver();
        this.$help.css('display', touches.wasTap ? 'block' : 'none');
        if (((_ref = touches.delta) != null ? _ref.x : void 0) === 0 && this.valStart === parseInt(this.$ele.val(), 10)) {
          this.$ele.select();
        }
      };

      DraggableNumber.prototype.updateRollOver = function() {
        this.updateStyle();
        this.updateCursor();
        this.updateHelp();
      };

      DraggableNumber.prototype.isActive = function() {
        return !this.isDragging && !root.isNumberDragging && this.isHovering;
      };

      DraggableNumber.prototype.updateStyle = function() {
        this.$ele.toggleClass('number-down', this.isDragging);
        this.$ele.toggleClass('number-hover', this.isActive());
      };

      DraggableNumber.prototype.updateCursor = function() {
        $('body').toggleClass('number-drag-cursor-h', this.isActive());
      };

      DraggableNumber.prototype.updateHelp = function() {
        var bt, d, l, pt, t;
        l = Math.round((this.$ele.outerWidth() - this.$help.width()) / 2);
        pt = this.$ele.css('paddingTop');
        bt = this.$ele.css('borderTopWidth');
        t = -this.$help.height() - (parseInt(pt, 10) + parseInt(bt, 10));
        d = this.isHovering && !root.isNumberDragging ? 'block' : 'none';
        this.$help.css({
          display: d,
          left: l,
          top: t
        });
      };

      return DraggableNumber;

    })();
    return DraggableNumber;
  });

}).call(this);
