// Generated by CoffeeScript 1.4.0
(function() {
  var define, log, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'input/job-type', 'touchable/draggable-number', 'chosen'], function($, JobType, DraggableNumber) {
    var Input;
    Input = (function() {

      function Input(el) {
        this.el = el;
        this.onChange = __bind(this.onChange, this);

        this.$el = $(this.el);
        this.jobType = new JobType();
        this.jobType.$el.prependTo(this.$el);
        this.$el.on('input change', this.onChange);
      }

      Input.prototype.onChange = function(event) {
        this.$el.find('.chzn-select').not('.chzn-done').each(function(i, el) {
          return $(el).chosen({
            allow_single_deselect: !!$(el).find('option[value=-1]').size(),
            disable_search_threshold: 20
          });
        });
        this.$el.find('input[type=number]').not('.draggable-number').each(function(i, el) {
          return new DraggableNumber(el);
        });
      };

      Input.prototype.clear = function() {
        return this.jobType.$el.find('#job-type').val(-1).trigger('liszt:updated').trigger('change');
      };

      return Input;

    })();
    return Input;
  });

}).call(this);
