// Generated by CoffeeScript 1.6.1
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'input/job-type', 'touchable/draggable-number', 'chosen'], function($, JobType, DraggableNumber) {
    var Input,
      _this = this;
    Input = (function() {

      function Input(el) {
        var _this = this;
        this.el = el;
        this.onChange = function(event) {
          return Input.prototype.onChange.apply(_this, arguments);
        };
        this.$el = $(this.el);
        this.jobType = new JobType();
        this.jobType.$el.prependTo(this.$el);
        this.$el.on('input change', this.onChange);
      }

      Input.prototype.onChange = function(event) {
        if ($('.no-touch').size() < 1) {
          this.$el.find('.chzn-select').each(function(i, el) {
            var $opt, isEmpty;
            $opt = $(this).find('option').first();
            isEmpty = $opt.text() === '';
            if (isEmpty) {
              $opt.text($(this).data('placeholder'));
            }
          });
        } else {
          this.$el.find('.chzn-select').not('.chzn-done').each(function(i, el) {
            return $(el).chosen({
              allow_single_deselect: !!$(el).find('option[value=-1]').size(),
              disable_search_threshold: 20
            });
          });
          this.$el.find('input[type=number]').not('.draggable-number').each(function(i, el) {
            return new DraggableNumber(el);
          });
          return;
        }
      };

      Input.prototype.clear = function() {
        return this.jobType.$el.find('#job-type').val(-1).trigger('liszt:updated').trigger('change');
      };

      return Input;

    })();
    return Input;
  });

}).call(this);
