// Generated by CoffeeScript 1.6.1
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'input/input', 'output/output'], function($, Input, Output) {
    var App,
      _this = this;
    App = (function() {

      function App(el) {
        var _this = this;
        this.el = el;
        this.onChange = function(event, isReset) {
          if (isReset == null) {
            isReset = false;
          }
          return App.prototype.onChange.apply(_this, arguments);
        };
        this.updateCount = 0;
        this.updateCountToCTA = 10;
        this.$el = $(this.el);
        this.input = new Input(this.$el.find('#input')[0]);
        this.output = new Output(this.$el.find('#output')[0]);
        this.input.$el.on('input change', this.output.onChange);
        this.$el.on('input change', this.onChange);
      }

      App.prototype.start = function() {};

      App.prototype.onChange = function(event, isReset) {
        if (isReset == null) {
          isReset = false;
        }
        this.$el.trigger('update');
        $('div.tooltip').filter(":visible").fadeOut(400);
        this.calcHeight();
        if (isReset) {
          this.updateCount = 0;
          return;
        }
        if (event.target.id === 'job-type') {
          this.updateCount = 0;
          $('#output-cta').fadeOut(400);
          $('#input-cta').fadeOut(400);
          return;
        }
        if (this.updateCount < this.updateCountToCTA) {
          this.updateCount++;
          if (this.updateCount === this.updateCountToCTA) {
            $('#output-cta').fadeIn(400);
            $('#input-cta').fadeIn(400);
            this.calcHeight();
          }
        }
      };

      App.prototype.calcHeight = function() {
        var height;
        height = Math.max(this.input.$el.css('height', 'auto').height(), this.output.$el.css('height', 'auto').height());
        this.input.$el.height(height);
        this.output.$el.height(height);
      };

      App.prototype.restart = function() {
        this.input.clear();
        return this.output.clear();
      };

      return App;

    })();
    return App;
  });

}).call(this);
