// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = window;

  root.sag_aftra_rates = {
    radio_commercial: {
      session_actor: 262.85,
      session_singer: 262.85,
      tag_2_25: 108.75,
      tag_26_50: 78.05,
      tag_51: 42.60,
      wild_13_unit_2_25: 3.86,
      wild_13_unit_26: 2.91,
      wild_13_major_new_york: 393.55,
      wild_13_major_chicago: 356.95,
      wild_13_major_los_angeles: 356.95,
      wild_13_major_any_2: 480.00,
      wild_13_major_all_3: 606.50,
      wild_8_unit_2_25: 3.86 * 0.8,
      wild_8_unit_26: 2.91 * 0.8,
      wild_8_major_new_york: 393.55 * 0.8,
      wild_8_major_chicago: 356.95 * 0.8,
      wild_8_major_los_angeles: 356.95 * 0.8,
      wild_8_major_any_2: 480.00 * 0.8,
      wild_8_major_all_3: 606.50 * 0.8,
      dealer_actor: 710.80,
      dealer_singer: 563.85,
      network_1: 444.75,
      network_4: 721.55,
      network_8: 1149.40,
      network_13: 1426.30,
      network_13_limited_26: 713.20,
      network_13_limited_39: 1074.05,
      regional_network: 860.70,
      internet_8_week: 349.60,
      internet_1_year: 920.00
    },
    radio_commercial_demo: {
      session_actor: 181.15,
      session_singer: 182.80
    },
    television_commercial_on_camera: {
      session_actor: 592.20,
      session_extra: 323.00,
      actor_wardrobe: 592.20 / 8,
      extra_wardrobe: 323.00 / 8,
      wild_13_unit_2_25: 20.27,
      wild_13_unit_26: 7.52,
      wild_13_major_new_york: 1163.80,
      wild_13_major_chicago: 1014.45,
      wild_13_major_los_angeles: 1014.45,
      wild_13_major_any_2: 1601.60,
      wild_13_major_all_3: 1931.85
    },
    television_commercial_off_camera: {
      session_actor: 445.30,
      tag_2_25: 132.45,
      tag_26_50: 73.50,
      tag_51: 40.05
    },
    television_commercial_demo: {
      session_actor: 445.30
    },
    psa_radio: {
      session_actor: 594.65,
      session_singer: 617.50
    },
    psa_television_on_camera: {
      session_actor: 592.20,
      session_extra: 323.00,
      actor_wardrobe: 592.20 / 8,
      extra_wardrobe: 323.00 / 8
    },
    psa_television_off_camera: {
      session_actor: 445.30,
      tag_2_25: 132.45,
      tag_26_50: 73.50,
      tag_51: 40.05
    },
    corp_edu_on_camera: {
      cat_1_session_narrator_day_1: 891.00,
      cat_1_session_narrator_day_2: 490.00,
      cat_1_session_player_half_day: 318.50,
      cat_1_session_player_day_1: 490.00,
      cat_1_session_player_day_3: 1233.00,
      cat_1_session_player_week: 1721.50,
      cat_1_session_extra_general: 127.50,
      cat_1_session_extra_special: 140.50,
      cat_1_session_extra_silent: 238.00,
      cat_2_session_narrator_day_1: 1056.00,
      cat_2_session_narrator_day_2: 609.50,
      cat_2_session_player_half_day: 396.00,
      cat_2_session_player_day_1: 609.50,
      cat_2_session_player_day_3: 1520.50,
      cat_2_session_player_week: 2344.50,
      cat_2_session_extra_general: 127.50,
      cat_2_session_extra_special: 140.50,
      cat_2_session_extra_silent: 238.00
    },
    corp_edu_off_camera: {
      cat_1_session_actor_first_hour: 401.00,
      cat_1_session_actor_addl_half: 117.50,
      cat_2_session_actor_first_hour: 446.50,
      cat_2_session_actor_addl_half: 117.50
    },
    corp_edu_audio_only: {
      cat_1_session_actor_first_hour: 393.00,
      cat_1_session_actor_addl_half: 115.00,
      cat_2_session_actor_first_hour: 437.50,
      cat_2_session_actor_addl_half: 115.00,
      ivr_session_actor_first_hour: 223.00,
      ivr_session_actor_addl_half: 111.00,
      store_session_actor_first_hour: 223.00,
      store_session_actor_addl_half: 111.00,
      store_use_3_month: 401.00,
      store_use_6_month: 802.00
    }
  };

}).call(this);
