// Generated by CoffeeScript 1.4.0
(function() {
  // var define, log, root;

  // root = this;

  // log = root.log;

  // define = root.define;

  define(['jquery', 'underscore', 'input/corp-edu/corp-edu-on-camera', 'input/corp-edu/corp-edu-off-camera', 'input/corp-edu/corp-edu-audio-only'], function($, _, CorpEduOnCamera, CorpEduOffCamera, CorpEduAudioOnly) {
    var exports;
    exports = {
      'OnCamera': CorpEduOnCamera,
      'OffCamera': CorpEduOffCamera,
      'AudioOnly': CorpEduAudioOnly
    };
    return exports;
  });

}).call(this);
