// Generated by CoffeeScript 1.3.3
(function() {
  var define, log, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'underscore'], function($, _) {
    var Category;
    Category = (function() {

      function Category() {
        this.onChange = __bind(this.onChange, this);
        this.html = "<fieldset>\n	It's a\n	<select name=\"category\" id=\"category\" class=\"chzn-select\" data-placeholder=\"please choose...\">\n		<!-- USER MUST CHOOSE A CATEGORY! -->\n		<!-- <option value=\"-1\"></option> -->\n	</select>\n	program.\n</fieldset>";
        this.$el = $(this.html);
        this.el = this.$el[0];
        this.setupOptions();
        this.$el.on('change', '#category', this.onChange);
      }

      Category.prototype.setupOptions = function() {
        var html;
        this.selectedIndex = -1;
        this.selectedItem = null;
        this.options = ['Category I', 'Category II'];
        html = '';
        _.each(this.options, function(el, i) {
          return html += "<option value=\"" + (i + 1) + "\">" + el + "</option>";
        });
        return this.$el.find('select').append(html);
      };

      Category.prototype.getSelectedItem = function() {
        return this.selectedItem;
      };

      Category.prototype.onChange = function(event) {
        this.selectedIndex = parseInt(event.target.value, 10);
        return this.selectedItem = this.selectedIndex !== -1 ? this.options[this.selectedIndex] : null;
      };

      return Category;

    })();
    return Category;
  });

}).call(this);
