// Generated by CoffeeScript 1.4.0
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery'], function($) {
    var PlayerDay;
    PlayerDay = (function() {

      function PlayerDay(index) {
        this.index = index;
        this.html = "<p>\n	I'll need day player " + this.index + " for\n	<input type=\"number\" name=\"player-" + this.index + "-num-days\" id=\"player-" + this.index + "-num-days\" class=\"num-days\" value=\"1\" min=\"0.5\" max=\"10\" step=\"0.5\">\n	day(s).\n</p>\n";
        this.$el = $(this.html);
        this.el = this.$el[0];
      }

      return PlayerDay;

    })();
    return PlayerDay;
  });

}).call(this);
