// Generated by CoffeeScript 1.4.0
(function() {
  // var define, log, root;

  // root = this;

  // log = root.log;

  // define = root.define;

  define(['jquery', 'underscore'], function($, _) {
    var Internet1Year;
    Internet1Year = (function() {

      function Internet1Year() {
        this.label = "1 Year Option";
        this.html = "<!-- NO OP -->";
        this.$el = $(this.html);
        this.el = this.$el[0];
      }

      return Internet1Year;

    })();
    return Internet1Year;
  });

}).call(this);
