// Generated by CoffeeScript 1.4.0
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'underscore', 'input/psa/psa-radio', 'input/psa/psa-television-on-camera', 'input/psa/psa-television-off-camera'], function($, _, PublicServiceAnnouncementRadio, PublicServiceAnnouncementTelevisionOnCamera, PublicServiceAnnouncementTelevisionOffCamera) {
    var exports;
    exports = {
      'Radio': PublicServiceAnnouncementRadio,
      'OnCamera': PublicServiceAnnouncementTelevisionOnCamera,
      'OffCamera': PublicServiceAnnouncementTelevisionOffCamera
    };
    return exports;
  });

}).call(this);
