// Generated by CoffeeScript 1.3.3
(function() {
  var define, log, root;

  root = this;

  log = root.log;

  define = root.define;

  define(['jquery', 'underscore', 'input/radio/radio-commercial', 'input/radio/radio-commercial-demo'], function($, _, RadioCommercial, RadioCommercialDemo) {
    var exports;
    exports = {
      'Commercial': RadioCommercial,
      'Demo': RadioCommercialDemo
    };
    return exports;
  });

}).call(this);
