// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = window;

  root.sag_aftra_rates = {
    radio_commercial: {
      session_actor: 262.85,
      session_singer: 262.85,
      tag_2_25: 108.75,
      tag_26_50: 78.05,
      tag_51: 42.60,
      wild_13_unit_2_25: 3.86,
      wild_13_unit_26: 2.91,
      wild_13_major_new_york: 393.55,
      wild_13_major_chicago: 356.95,
      wild_13_major_los_angeles: 356.95,
      wild_13_major_any_2: 480.00,
      wild_13_major_all_3: 606.50,
      wild_8_unit_2_25: 3.86 * 0.8,
      wild_8_unit_26: 2.91 * 0.8,
      wild_8_major_new_york: 393.55 * 0.8,
      wild_8_major_chicago: 356.95 * 0.8,
      wild_8_major_los_angeles: 356.95 * 0.8,
      wild_8_major_any_2: 480.00 * 0.8,
      wild_8_major_all_3: 606.50 * 0.8,
      dealer_actor: 710.80,
      dealer_singer: 563.85,
      network_1: 444.75,
      network_4: 721.55,
      network_8: 1149.40,
      network_13: 1426.30,
      network_13_limited_26: 713.20,
      network_13_limited_39: 1074.05,
      regional_network: 860.70,
      internet_8_week: 349.60,
      internet_1_year: 920.00
    },
    radio_commercial_demo: {
      session_actor: 181.15,
      session_singer: 182.80
    },
    television_commercial_on_camera: {
      session_actor: 592.20,
      session_extra: 323.00,
      actor_wardrobe: 592.20 / 8,
      extra_wardrobe: 323.00 / 8,
      wild_13_unit_2_25: 20.27,
      wild_13_unit_26: 7.52,
      wild_13_major_new_york: 1163.80,
      wild_13_major_chicago: 1014.45,
      wild_13_major_los_angeles: 1014.45,
      wild_13_major_any_2: 1601.60,
      wild_13_major_all_3: 1931.85,
      local_1_50k: 26.15,
      local_50k_100k: 52.55,
      local_100k_150k: 78.70,
      local_150k_200k: 104.95,
      local_200k_250k: 131.10,
      local_250k_500k: 262.40,
      local_500k_750k: 393.50,
      local_750k_1m: 524.65,
      national_min: 592.20,
      national_1_50: 9.95,
      national_51_100: 8.64,
      national_101_150: 7.34,
      national_151_200: 6.03,
      national_201_1k: 0.71,
      national_1k_2k: 0.67,
      national_max: 2836.50,
      network_2: 135.80,
      network_3: 107.75,
      network_4_13: 107.75,
      network_14: 51.65,
      internet_8_week: 787.65,
      internet_1_year: 2072.70
    },
    television_commercial_off_camera: {
      session_actor: 445.30,
      tag_2_25: 132.45,
      tag_26_50: 73.50,
      tag_51: 40.05,
      wild_13_unit_2_25: 13.87,
      wild_13_unit_26: 5.90,
      wild_13_major_new_york: 822.20,
      wild_13_major_chicago: 715.45,
      wild_13_major_los_angeles: 715.45,
      wild_13_major_any_2: 1078.40,
      wild_13_major_all_3: 1372.10,
      local_1_50k: 17.85,
      local_50k_100k: 35.90,
      local_100k_150k: 53.85,
      local_150k_200k: 71.85,
      local_200k_250k: 89.75,
      local_250k_500k: 179.65,
      local_500k_750k: 269.40,
      local_750k_1m: 359.25,
      network_2: 106.25,
      network_3: 84.55,
      network_4_13: 84.55,
      network_14: 38.40,
      internet_8_week: 592.25,
      internet_1_year: 1558.55
    },
    television_commercial_demo: {
      session_actor: 445.30
    },
    psa_radio: {
      session_actor: 594.65,
      session_singer: 617.50
    },
    psa_television_on_camera: {
      session_actor: 592.20,
      session_extra: 323.00,
      actor_wardrobe: 592.20 / 8,
      extra_wardrobe: 323.00 / 8
    },
    psa_television_off_camera: {
      session_actor: 445.30,
      tag_2_25: 132.45,
      tag_26_50: 73.50,
      tag_51: 40.05
    },
    corp_edu_on_camera: {
      cat_1_session_narrator_day_1: 891.00,
      cat_1_session_narrator_day_2: 490.00,
      cat_1_session_player_half_day: 318.50,
      cat_1_session_player_day_1: 490.00,
      cat_1_session_player_day_3: 1233.00,
      cat_1_session_player_week: 1721.50,
      cat_1_session_extra_general: 127.50,
      cat_1_session_extra_special: 140.50,
      cat_1_session_extra_silent: 238.00,
      cat_2_session_narrator_day_1: 1056.00,
      cat_2_session_narrator_day_2: 609.50,
      cat_2_session_player_half_day: 396.00,
      cat_2_session_player_day_1: 609.50,
      cat_2_session_player_day_3: 1520.50,
      cat_2_session_player_week: 2344.50,
      cat_2_session_extra_general: 127.50,
      cat_2_session_extra_special: 140.50,
      cat_2_session_extra_silent: 238.00
    },
    corp_edu_off_camera: {
      cat_1_session_actor_first_hour: 401.00,
      cat_1_session_actor_addl_half: 117.50,
      cat_2_session_actor_first_hour: 446.50,
      cat_2_session_actor_addl_half: 117.50
    },
    corp_edu_audio_only: {
      cat_1_session_actor_first_hour: 401.00,
      cat_1_session_actor_addl_half: 117.50,
      cat_2_session_actor_first_hour: 446.50,
      cat_2_session_actor_addl_half: 117.50,
      ivr_session_actor_first_hour: 223.00,
      ivr_session_actor_addl_half: 111.00,
      store_3_month_session_actor_first_hour: 401.00,
      store_3_month_session_actor_addl_half: 117.50,
      store_6_month_session_actor_first_hour: 802.00,
      store_6_month_session_actor_addl_half: 117.50
    }
  };

}).call(this);
